<h1>Python  Basics </h1>

**Source**: AI4ALL

Let us start with some simple Python exercises. 

### REVIEW (*in* operator and functions):

What is the 'in' operator? It returns a Boolean (True or False) when you (typically) ask if 'x' is in a list (or even a string).

For example, run the following code. It should output _True_.

In [0]:
# This code demonstrates the use of the 'in' operator

x = 5
y = x in [1, 2, 3, 4, 5]

print('This should say True:', y)

In [0]:
# This piece of code demonstrates the use of the 'in' operator too

character = "L"
if character in "AI4ALL":
    print('True')
    
# It can also be used like this
if "under" in "understand":
    print('Substring found!')

In [0]:
# Now you try it! Is there an "i" in "team"?

string = "team"
x = "i"

answer = Python  # repalce Python with your solution
print(answer)

How does a function work? 

If you run the function below, it should return "Hello"

In [0]:
# This function called example will return "Hello"

def example():
    return "Hello"

Hmmm, wait, that didn't return "Hello" though! It didn't return anything!

Now, what do we need to do to see our output?

Well, if you wondered where the function call is, you wondered right! You cannot see the return value of a function without calling it.

In [0]:
example()

Can you answer this? What is the difference between func1 and func2? Run them to see!

In [4]:
# Function 1: func1

def func1():
    return 'True'

# function call
func1()

'True'

In [5]:
# Function 2: func2

def func2():
    return True

# function call
func2()

True

They both look the same: 'True' vs True. The difference is that 'True' is a string and True is a Boolean. So now you know that the booleans True and False do not need to be in quotes while returning.

Now, time to do it yourself!

**Exercise 1:** 

The parameter _weekday_ is _True_ if it is a weekday, and the parameter _vacation_ is _True_ if we are on vacation. We sleep in if it is **not** a weekday or we're on vacation. Return _True_ if we sleep in.

In [43]:
# Exercise 1

# sleep_in(False, False) → True
# sleep_in(True, False) → False
# sleep_in(False, True) → True

def sleep_in(weekday, vacation):
  if weekday == True and vacation == False:
    return False
  else:
    return True
  
sleep_in(False, True)

True

In [44]:
# Now, test it by running this!

# TEST 1: Not a weekday, and not on vacation. 
print(sleep_in(False, False))  # should return True 

# TEST 2: Is a weekday, and not on vacation. 
print(sleep_in(True, False))  # should return False

# TEST 3: Not a weekday, and on vacation. 
print(sleep_in(False, True))  # should return True 

# TEST 4: Is a weekday, and on vacation. 
print(sleep_in(True, True))  # should return True

True
False
True
True

### REVIEW (Strings - slicing and more!):

What is a string? A string is a sequence of characters. It is represented in single quotes (' ') or double quotes (" ").

How do you find the length of a string? Run the line of code below to see how!

In [13]:
print(len('Hello'))

5

In [0]:
string = 'I love Python!'

# Before you run this cell, can you guess the length of the string above?

print(len(string))

**Remember** that digits (0-9), spaces, and special characters (!,.% and more) are also characters. The _len_ function counts the number of characters in a string.

Now, what is **concatenation**? Concatenation means joining string together. We can do this with the '+' operator in Python. 

You may be wondering: If this is used for concatenation, how do we add numbers in Python?

Answer: The '+' operator works as a concatenator when the "arguments" are strings, whereas it works as a regular math plus sign when the "arguments" are numbers (integer, float, double, etc...)

'Hi' + 'There' = 'HiThere'

1 + 4 = 5

Here, 'Hi', 'There', 1, and 4 are the arguments.

**Think about this!**
What happens when we try to do this: 'Hi' + 4? Run the cell below to find out!

In [14]:
# This will give you a TypeError - which means you CANNOT use + on two different data types.

print('Hi' + 4)

TypeError: ignored

How about if we did this instead: 'Hi' + '4'? Run the cell below to find out!

In [15]:
# To solve the problem above to get Hi4 as the output, enclose the 4 in quotes like this - '4'

print('Hi' + '4')

Hi4

Similarly, the * operator performs multiplication. When used with strings, it works like this:

In [16]:
print('AI4ALL' * 2) 
print('Hey' * 3)

my_str = 'CS'
print(my_str * 5)

AI4ALLAI4ALL
HeyHeyHey
CSCSCSCSCS

Now, time to review slicing from the slides! Here are a few examples for you. Let us know if you have any questions!

In [0]:
string = 'AI4ALL'

In [18]:
print(string[1:])

I4ALL

In [19]:
print(string[:-1])

AI4AL

In [20]:
print(string[0:])

AI4ALL

In [21]:
print(string[0:-1])

AI4AL

In [22]:
print(string[1:2])

I

In [23]:
print(string[1:5])  # This is equivalent to print(str[1:-1])
print(string[1:-1])

I4AL
I4AL

In [0]:
print(string[1:1])

In [0]:
print(string[1:4])

In [24]:
print(string[:6])

AI4ALL

In [25]:
print(string[:7])   # change 7 to numbers greater than 7 and see what happens

AI4ALL

Now that you know how to perform some basic string operations, here are a few exercises.

**Exercise 2:**

Given a string, we'll say that the front is the first 3 chars of the string. If the string length is less than 3, the front is whatever is there. Return a new string which is 3 copies of the front.

In [0]:
# Exercise 2

# front3('Java') → 'JavJavJav'
# front3('Chocolate') → 'ChoChoCho'
# front3('abc') → 'abcabcabc'

def front3(string):
    # YOUR CODE HERE

In [0]:
# Run this cell to test your code.

def tests():
    test1 = (front3('Java') == 'JavJavJav')
    test2 = (front3('Chocolate') == 'ChoChoCho')
    test3 = (front3('AI4ALL') == 'AI4AI4AI4')
    test4 = (front3('abc') == 'abcabcabc')
    test5 = (front3('') == '')
    test6 = (front3('Hi') == 'HiHiHi')
    
    if (test1 and test2 and test3 and test4 and test5 and test6) == True:
        print('All correct!')
    else:
        print('Something is wrong. Check your code again.')

tests()

Indexing: To access one character of a string 'str', you can just say str[0], or str[1], or str[-1] for the last character. Check out the examples below.

In [0]:
my_str1 = 'AI4ALLatBU'

print('First character:', my_str1[0])
print('Last character:', my_str1[len(my_str1) - 1])  # We do the -1 because indexing starts from 0 and not 1. Without the - 1 you will get an IndexError

# Better way to get the last character, without using len function:
print('Last character:', my_str1[-1])
print('Second character:', my_str1[1])
print('Second to last character (or 9th character):', my_str1[-2])

One more with slicing and concatenation! 

Note: When concatenating, if you want a space, you need to add one. For example,

In [0]:
print("Hello " + "World!")  # note space after Hello before the double quote closes.

**Exercise 3:**

Given a string, return a new string where "not " has been added to the front. However, if the string already begins with "not", return the string unchanged.

In [0]:
# Exercise 3

# not_string('candy') → 'not candy'
# not_string('x') → 'not x'
# not_string('not bad') → 'not bad'

def not_string(string):
    # YOUR CODE HERE

In [0]:
# Run this cell to test your code.

def tests():
    test1 = (not_string('candy') == 'not candy')
    test2 = (not_string('x') == 'not x')
    test3 = (not_string('not bad') == 'not bad')
    test4 = (not_string('bad') == 'not bad')
    test5 = (not_string('not') == 'not')
    test6 = (not_string('is not') == 'not is not')
    test7 = (not_string('no') == 'not no')
    
    if (test1 and test2 and test3 and test4 and test5 and test6 and test7) == True:
        print('All correct!')
    else:
        print('Something is wrong. Check your code again.')

tests()

**Exercise 4:**

Given a string and a non-negative int n, return a larger string that is n copies of the original string.

In [0]:
# Exercise 4
# This can be written in one line using the * operator. 

# string_times('Hi', 2) → 'HiHi'
# string_times('Hi', 3) → 'HiHiHi'
# string_times('Hi', 1) → 'Hi'

def string_times(string, n):
    # YOUR CODE HERE

In [0]:
# Run this cell to test your code.

def tests():
    test1 = (string_times('Hi', 2) == 'HiHi')
    test2 = (string_times('Hi', 3) == 'HiHiHi')
    test3 = (string_times('Hi', 1) == 'Hi')
    test4 = (string_times('Hi', 0) == '')
    test5 = (string_times('Oh Boy!', 2) == 'Oh Boy!Oh Boy!')
    test6 = (string_times('', 4) == '')
    test7 = (string_times('x', 4) == 'xxxx')
    
    if (test1 and test2 and test3 and test4 and test5 and test6 and test7) == True:
        print('All correct!')
    else:
        print('Something is wrong. Check your code again.')

tests()

**Exercise 5: The four Fours Challenge!**

In this problem you will write a simple Python program that computes the integers 0 through 4 using expressions involving exactly four fours and no other numbers. For example:

In [0]:
zero = 4 + 4 - 4 - 4
print('zero =', zero)

Your expressions may use any of the following operators: +, -, *, // (integer division), ** (power), and parentheses. Note that you should use the integer division operator (//) instead of the regular division operator (/), because the / operator will cause your results to include a decimal. For example, 4//4 will give you 1, but 4/4 will give you 1.0.

Follow the example above to write expressions to computer the integers one through four.

Your output should look like this:

```zero = 0 
one = 1 
two = 2 
three = 3
four = 4```

In [0]:
# YOUR CODE HERE - First one has been done for you. 

# Code for zero
zero = 4 + 4 - 4 - 4
print('zero =', zero)

# Code for one here


# Code for two here


# Code for three here


# Code for four here

### REVIEW - loops

Answer the following:

1) In simple words, what is a for loop?

2) How does the 'range' function work?

In [0]:
# Example loop 1
print('First Loop')
for i in range(0,10):
    print(i)
    
print('*********')

# Example loop 2
print('Second loop')
for i in range(10):
    print(i)
    
# What is the difference between Example loop 1 and 2? They print the same thing. 
# If the first number is not specified, it is 0 by default.

In [0]:
# Run this code, modify the arguments of the range function to see how it works. 
# Maybe you can remove or change 2 and 15. Make sure you don't enter really huge numbers, because that would run for a while.

for x in range(2,15):
    print('Hello', x)

Remember, there are two ways to loop:

- Using an index 
- Using an element

Look at this example - understand how they work.

In [0]:
lst = [6, 2, 4, 8, 0, 5, 11]

# Example loop 3
print('Using an index')
for i in range(len(lst)):  # index based loop
    print(lst[i])
    
# Example loop 4
print('Using an element')
for ele in lst:           # element based loop
    print(ele)
    
# Note that both have the same output, and each of them have different applications.
# Can you think of when an index based loop will be useful?

**Exercise 6:**

Return the number of even ints in the given array. Note: the % "mod" operator computes the remainder, e.g. 5 % 2 is 1.

In [0]:
# Exercise 6

# count_evens([2, 1, 2, 3, 4]) → 3
# count_evens([2, 2, 0]) → 3
# count_evens([1, 3, 5]) → 0

def count_evens(nums):
    ''' nums is the list of ints '''
    # YOUR CODE HERE

In [0]:
# Run this cell to test your code.

def tests():
    test1 = (count_evens([2, 1, 2, 3, 4]) == 3)
    test2 = (count_evens([2, 2, 0]) == 3)
    test3 = (count_evens([1, 3, 5]) == 0)
    test4 = (count_evens([]) == 0)
    test5 = (count_evens([11, 9, 0, 1]) == 1)
    test6 = (count_evens([2]) == 1)
    test7 = (count_evens([2, 5, 12]) == 2)
    
    if (test1 and test2 and test3 and test4 and test5 and test6 and test7) == True:
        print('All correct!')
    else:
        print('Something is wrong. Check your code again.')

tests()

What does a break statement do? Like the name suggests, it breaks out of the loop.

In [0]:
# Run this cell to test your code.

def tests():
    test1 = (sum13([1, 2, 2, 1]) == 6)
    test2 = (sum13([1, 13, 2]) == 1)
    test3 = (sum13([13]) == 0)
    test4 = (sum13([]) == 0)
    test5 = (sum13([1, 2, 2, 1, 13, 13, 4, 5]) == 6)
    test6 = (sum13([13, 6, 34, 1]) == 0)
    test7 = (sum13([13, 1, 13]) == 0)
    
    if (test1 and test2 and test3 and test4 and test5 and test6 and test7) == True:
        print('All correct!')
    else:
        print('Something is wrong. Check your code again.')

tests()

### REVIEW - If and else

If + else = elif

- When do you use if? 
- When do you use if and else?
- When do you use elif?

**Exercise 8:**

The number 6 is a truly great number. Given two int values, a and b, return True if either one is 6. Or if their sum or difference is 6. Note: the function abs(num) computes the absolute value of a number.

In [0]:
# Exercise 8 

# love6(6, 4) → True
# love6(4, 5) → False
# love6(1, 5) → True

def love6(a, b):
    # YOUR CODE HERE

In [0]:
# Run this cell to test your code.

def tests():
    test1 = (love6(6, 4) == True)
    test2 = (love6(4, 5) == False)
    test3 = (love6(1, 5) == True)
    test4 = (love6(1, 6) == True)
    test5 = (love6(1, 8) == False)
    test6 = (love6(1, 7) == True)
    test7 = (love6(7, 5) == False)
    test8 = (love6(-4, -10) == True)
    test9 = (love6(-7, 1) == False)
    test10 = (love6(7, -1) == True)
    test11 = (love6(-6, 12) == True)
    test12 = (love6(-2, -4) == False)
    test13 = (love6(0, 9) == False)
    test14 = (love6(3, 3) == True)
    
    if (test1 and test2 and test3 and test4 and test5 and test6 and test7 and test8 and test9 and test10 and test11 and test12 and test13 and test14) == True:
        print('All correct!')
    else:
        print('Something is wrong. Check your code again.')
    

tests()

Done with the easy set! Good job!